name: purepond_app
description: Aplikasi monitoring kolam PurePond
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  google_fonts: ^6.1.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.0.4
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

  mqtt_client: ^10.11.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_aplikasi.png"
  min_sdk_android: 23
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/images/logo_aplikasi.png"